name: Deploy to Tencent Cloud

on:
  push:
    branches:
       - main # 

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Tencent Cloud CLI
        uses: tencentcloud/tencentcloud-cli-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          region: ap-siliconvalley  

      - name: Deploy using TAT
        run: |
          tccli tat InvokeCommand --InstanceIds '["lhins-rv24ophb"]' --CommandContent 'Write-Host \"自动部署脚本测试成功！\"'
